# Generated by Django 4.1.7 on 2023-04-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=300)),
                ('actror', models.CharField(max_length=300)),
                ('actress', models.CharField(max_length=300)),
                ('release', models.DateField(verbose_name='Release Date')),
                ('statud', models.CharField(max_length=300)),
            ],
        ),
    ]
