# Generated by Django 4.1.7 on 2023-04-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='statud',
            new_name='status',
        ),
    ]
